name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build src/BattlenetApi/BattleNetApi.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - uses: einaregilsson/build-number@v1
      with:
        token: ${{secrets.github_token}}
    - name: Pack
      run: dotnet pack --configuration Release -p:PackageVersion=1.0.0.$BUILD_NUMBER src/BattlenetApi/BattleNetApi.csproj
    - name: Publish
      run: dotnet nuget push "src/BattlenetApi/bin/Release/ASoft.BattleNet.1.0.0.$BUILD_NUMBER.nupkg" --source nuget.org --api-key ${{ secrets.NuGetAPIKey }}

